# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r: bioc-devel

cache:
  packages: true

r: 3.5.0

os:
  - linux

env:
  global:
    - R_CHECK_ARGS="--no-build-vignettes --no-manual"

install:
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh install_bioc_deps

after_script:
  - ./travis-tool.sh dump_logs_by_extension "timings"
  - ./travis-tool.sh dump_sysinfo

notifications:
  email:
    on_success: change
    on_failure: change


