# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages


r:3.6.0

bioc_packages:
  - hopach
  - BiocGenerics
os:
  - linux
  - osx
#matrix:
#  include:
#  - r: devel
#  - r: release
#    after_success:
#    - Rscript -e 'covr::codecov()'
#  - r: oldrel
#  - r: 3.3
#  - r: 3.2
#  - r: 3.1
