# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

r: 
  - 3.5

os:
    - linux

# safelist
branches:
  only:
  - master

addons:
  apt:
    packages:
      - python3.5
      - python-numpy
      - python-scipy
      - python-sklearn

# Install Bioconductor dependencies
bioc_packages:
  - BiocGenerics
  - Biostrings
  - hopach
  - TFBSTools  

warnings_are_errors: true


env:
  global:
  # don't treat missing suggested packages as error
  - _R_CHECK_FORCE_SUGGESTS_=false
  # switch off vdiffr by default
  - VDIFFR_RUN_TESTS=false

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
