# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache: packages

r: 
  - 3.5

os:
    - linux

addons:
  apt:
    packages:
      - python3.5
      - python-numpy
      - python-scipy
      - python-sklearn


before_install:
  Rscript -e 'BiocManager::install(c("hopach", "Biostrings", "BiocGenerics"), update = TRUE)'

warnings_are_errors: true

