name: R Build and Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: R Build and Checks
      uses: Swechhya/R-actions@v1.2
      with:
        action: 'all'
        needsBioc: true
